version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-cache:/data
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=tsegen
    - MONGO_INITDB_ROOT_PASSWORD=mypassword
  server:
    ports:
      - '8080:8080'
    volumes:
      - ./blitser:/app
    env_file:
      - ./blitser/.env
    environment:
      - PORT=8080
      - NODE_ENV=development
      - DATABASE_URL=mongodb://127.0.0.1:27017/blitser
    depends_on:
      - mongo
    command: ["npm","run","dev"]




volumes:
  mongo-db: